[package]
name = "learn_pltl_fast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.*"
rayon = "1.5.*"
ron = "0.7.*"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.11"
# z3 = "0.11.*"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "sample"
harness = false